# Generated by Django 5.0 on 2024-01-08 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
        ('fights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneylineBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('placed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('W', 'Won'), ('L', 'Lost'), ('P', 'Pending'), ('R', 'Returned')], default='P', max_length=1)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chosen_fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_for_moneyline', to='fighters.fighter')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyline_bets', to='fights.upcomingfight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalsBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('placed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('W', 'Won'), ('L', 'Lost'), ('P', 'Pending'), ('R', 'Returned')], default='P', max_length=1)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_rounds', models.IntegerField(choices=[(1, '1.5 Rounds'), (2, '2.5 Rounds'), (3, '3.5 Rounds'), (4, '4.5 Rounds')])),
                ('over_or_under', models.CharField(choices=[('O', 'Over'), ('U', 'Under')], max_length=1)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totals_bets', to='fights.upcomingfight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
