# Generated by Django 5.0 on 2024-01-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='coin',
            new_name='hitcoin',
        ),
    ]
