# Generated by Django 5.0 on 2024-01-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_fighter_id', models.IntegerField(blank=True, null=True)),
                ('final_round', models.IntegerField(blank=True, null=True)),
                ('victory_type', models.CharField(choices=[('DI', 'Distance'), ('KO', 'Knockout'), ('SU', 'Submission'), ('XX', 'Death'), ('NC', 'No Contest')], default='DI', max_length=2)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('fighter_a_id', models.ForeignKey(limit_choices_to={'is_banished': False, 'is_deceased': False, 'is_enlightened': False, 'is_exiled': False, 'is_retired': False}, on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_fighter_a', to='fighters.fighter')),
                ('fighter_b_id', models.ForeignKey(limit_choices_to={'is_banished': False, 'is_deceased': False, 'is_enlightened': False, 'is_exiled': False, 'is_retired': False}, on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_fighter_b', to='fighters.fighter')),
            ],
        ),
        migrations.CreateModel(
            name='FightDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField()),
                ('action_attempted', models.CharField(choices=[('NA', 'No Action'), ('AT', 'Attack'), ('TD', 'Takedown Attempt'), ('RV', 'Reversal Attempt'), ('BA', 'Breakaway Attempt')], default='NA', max_length=2)),
                ('sub_action_attempted', models.CharField(blank=True, max_length=32, null=True)),
                ('aggressor_position', models.CharField(blank=True, choices=[('W', 'Victory'), ('L', 'Defeat'), ('DG', 'Dominant Ground'), ('UG', 'Unsecure Ground'), ('VG', 'Vulnerable Ground'), ('CL', 'Clinch'), ('DI', 'Distance')], max_length=2, null=True)),
                ('action_details', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('step_number', models.IntegerField()),
                ('aggressor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fightdetails_as_aggressor', to='fights.fight')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fightdetails_as_defender', to='fights.fight')),
                ('fight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fightdetails', to='fights.fight')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='UpcomingFight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('fighter_a_id', models.ForeignKey(limit_choices_to={'is_banished': False, 'is_deceased': False, 'is_enlightened': False, 'is_exiled': False, 'is_retired': False}, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_fights_as_fighter_a', to='fighters.fighter')),
                ('fighter_b_id', models.ForeignKey(limit_choices_to={'is_banished': False, 'is_deceased': False, 'is_enlightened': False, 'is_exiled': False, 'is_retired': False}, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_fights_as_fighter_b', to='fighters.fighter')),
            ],
        ),
    ]
