# Generated by Django 5.0 on 2023-12-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FightDetails',
            new_name='FightDetail',
        ),
    ]
