# Generated by Django 5.0 on 2023-12-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('prefix', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('suffix', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=768, verbose_name='F(prefix) F(name) F(suffix)')),
                ('bio', models.CharField(max_length=2048, null=True)),
                ('is_athiest', models.BooleanField()),
                ('is_abstinent', models.BooleanField()),
                ('is_badboy', models.BooleanField()),
                ('is_derranged', models.BooleanField()),
                ('is_radioactive', models.BooleanField()),
                ('is_offensive', models.BooleanField()),
                ('is_on_drugs', models.BooleanField(default=False)),
                ('is_infected', models.BooleanField(default=False)),
                ('is_injured', models.BooleanField(default=False)),
                ('is_retired', models.BooleanField(default=False)),
                ('is_deceased', models.BooleanField(default=False)),
                ('has_visited_ancient_temple', models.BooleanField(default=False, null=True)),
                ('has_monastic_training', models.BooleanField(default=False, null=True)),
                ('is_roastmaster', models.BooleanField(default=False, null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('reach', models.IntegerField()),
                ('stance', models.CharField(choices=[('OR', 'Orthodox'), ('SW', 'Sideways'), ('SP', 'Southpaw'), ('OS', 'Open Stance'), ('IL', 'Illegal')], default='OR', max_length=2)),
                ('strike_attempt_successes', models.IntegerField()),
                ('strike_attempt_failures', models.IntegerField()),
                ('strike_defense_successes', models.IntegerField()),
                ('strike_defense_failures', models.IntegerField()),
                ('sig_strike_attempt_successes', models.IntegerField()),
                ('sig_strike_attempt_failures', models.IntegerField()),
                ('head_strike_attempts', models.IntegerField()),
                ('body_strike_attempts', models.IntegerField()),
                ('leg_strike_attempts', models.IntegerField()),
                ('takedown_attempt_successes', models.IntegerField()),
                ('takedown_attempt_failures', models.IntegerField()),
                ('takedown_defense_successes', models.IntegerField()),
                ('takedown_defense_failures', models.IntegerField()),
                ('submission_attempt_successes', models.IntegerField()),
                ('submission_attempt_failures', models.IntegerField()),
                ('submission_defense_successes', models.IntegerField()),
                ('submission_defense_failures', models.IntegerField()),
                ('control_time_success', models.IntegerField()),
                ('control_time_failure', models.IntegerField()),
                ('total_fight_time', models.FloatField()),
                ('knock_downs', models.IntegerField()),
            ],
        ),
    ]
