# Generated by Django 5.0 on 2023-12-14 03:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('HAIR', 'Hair'), ('EYE', 'Eyes'), ('EAR', 'Ears'), ('BEARD', 'Beard'), ('MOUTH', 'Mouth'), ('NECK', 'Neck'), ('BODY', 'Body'), ('ARM', 'Arms'), ('GLOVES', 'Gloves'), ('SHORTS', 'Shorts'), ('LEG', 'Legs'), ('FEET', 'Feet'), ('TATTOO', 'Tattoos')], max_length=8)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Exotic'), ('L', 'Legendary')], default='C', max_length=1)),
                ('primary_color', models.CharField(blank=True, max_length=16, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=16, null=True)),
                ('tertiary_color', models.CharField(blank=True, max_length=16, null=True)),
                ('color_shift_r', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('color_shift_g', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('color_shift_b', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('img', models.ImageField(upload_to='')),
                ('metadata', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('prefix', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('suffix', models.CharField(max_length=256)),
                ('bio', models.CharField(max_length=2048, null=True)),
                ('is_athiest', models.BooleanField()),
                ('is_abstinent', models.BooleanField()),
                ('is_badboy', models.BooleanField()),
                ('is_derranged', models.BooleanField()),
                ('is_offensive', models.BooleanField()),
                ('is_radioactive', models.BooleanField()),
                ('is_infected', models.BooleanField(default=False)),
                ('is_injured', models.BooleanField(default=False)),
                ('is_intoxicated', models.BooleanField(default=False)),
                ('is_incarcerated', models.BooleanField(default=False)),
                ('is_enlightened', models.BooleanField(default=False)),
                ('is_banished', models.BooleanField(default=False)),
                ('is_exiled', models.BooleanField(default=False)),
                ('is_retired', models.BooleanField(default=False)),
                ('is_deceased', models.BooleanField(default=False)),
                ('has_visited_ancient_temple', models.BooleanField(default=False, null=True)),
                ('has_monastic_training', models.BooleanField(default=False, null=True)),
                ('is_roastmaster', models.BooleanField(default=False, null=True)),
                ('is_rehabilitated', models.BooleanField(default=False, null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('reach', models.IntegerField()),
                ('stance', models.CharField(choices=[('OR', 'Orthodox'), ('SW', 'Sideways'), ('SP', 'Southpaw'), ('OS', 'Open Stance'), ('KY', 'Kentucky'), ('IL', 'Illegal')], default='OR', max_length=2)),
                ('stats', models.JSONField(default=dict)),
                ('cosmetic_arm', models.ForeignKey(blank=True, limit_choices_to={'type': 'ARM'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_arm', to='fighters.cosmetic')),
                ('cosmetic_beard', models.ForeignKey(blank=True, limit_choices_to={'type': 'BEARD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_beard', to='fighters.cosmetic')),
                ('cosmetic_body', models.ForeignKey(blank=True, limit_choices_to={'type': 'BODY'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_body', to='fighters.cosmetic')),
                ('cosmetic_ear', models.ForeignKey(blank=True, limit_choices_to={'type': 'EAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_ear', to='fighters.cosmetic')),
                ('cosmetic_eye', models.ForeignKey(blank=True, limit_choices_to={'type': 'EYE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_eye', to='fighters.cosmetic')),
                ('cosmetic_feet', models.ForeignKey(blank=True, limit_choices_to={'type': 'FEET'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_feet', to='fighters.cosmetic')),
                ('cosmetic_gloves', models.ForeignKey(blank=True, limit_choices_to={'type': 'GLOVES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_gloves', to='fighters.cosmetic')),
                ('cosmetic_hair', models.ForeignKey(blank=True, limit_choices_to={'type': 'HAIR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_hair', to='fighters.cosmetic')),
                ('cosmetic_leg', models.ForeignKey(blank=True, limit_choices_to={'type': 'LEG'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_leg', to='fighters.cosmetic')),
                ('cosmetic_mouth', models.ForeignKey(blank=True, limit_choices_to={'type': 'MOUTH'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_mouth', to='fighters.cosmetic')),
                ('cosmetic_neck', models.ForeignKey(blank=True, limit_choices_to={'type': 'NECK'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_neck', to='fighters.cosmetic')),
                ('cosmetic_shorts', models.ForeignKey(blank=True, limit_choices_to={'type': 'SHORTS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_shorts', to='fighters.cosmetic')),
                ('cosmetic_tattoo', models.ForeignKey(blank=True, limit_choices_to={'type': 'TATTOO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters_tattoo', to='fighters.cosmetic')),
            ],
        ),
    ]
