# Generated by Django 5.0 on 2024-01-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Name'), ('P', 'Prefix'), ('S', 'Suffix')], max_length=1)),
                ('text', models.CharField(max_length=64)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Exotic'), ('L', 'Legendary')], default='C', max_length=1)),
            ],
        ),
    ]
