# Generated by Django 5.0 on 2024-01-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_fightername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FighterName',
            new_name='Name',
        ),
    ]
