# Generated by Django 5.0 on 2024-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_rename_fightername_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='is_emaciated',
            field=models.BooleanField(default=False),
        ),
    ]
