# Generated by Django 5.0 on 2024-01-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_fighter_is_emaciated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Exotic'), ('L', 'Legendary')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='stance',
            field=models.CharField(choices=[('OR', 'Orthodox'), ('SW', 'Switch'), ('SP', 'Southpaw'), ('OS', 'Open Stance'), ('KY', 'Kentucky'), ('IR', 'Irish'), ('MA', 'Mantis'), ('TI', 'Tiger'), ('WB', 'Water Buffalo'), ('IL', 'Illegal')], default='OR', max_length=2),
        ),
    ]
