# Generated by Django 5.0 on 2024-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0005_fighter_rarity_alter_fighter_stance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='stats',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='stance',
            field=models.CharField(choices=[('OR', 'Orthodox'), ('SW', 'Switch'), ('SP', 'Southpaw'), ('OS', 'Open Stance'), ('KY', 'Kentucky'), ('IR', 'Irish'), ('MA', 'Mantis'), ('TI', 'Tiger'), ('WB', 'Water Buffalo'), ('WO', 'Wooshi'), ('IL', 'Illegal')], default='OR', max_length=2),
        ),
    ]
