# Generated by Django 5.0 on 2024-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0006_fighter_stats_alter_fighter_stance'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritfighter',
            name='reach',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
