# Generated by Django 5.0 on 2024-01-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0007_spiritfighter_reach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='stats',
            new_name='priors',
        ),
    ]
