# Generated by Django 5.0 on 2024-01-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0009_remove_cosmetic_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetic',
            name='color_shift_b',
        ),
        migrations.RemoveField(
            model_name='cosmetic',
            name='color_shift_g',
        ),
        migrations.RemoveField(
            model_name='cosmetic',
            name='color_shift_r',
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='color_data',
            field=models.JSONField(default={'auto_find_colors': True, 'constant_colors': {}, 'independent_color_shift': {}, 'is_color_shifted': False, 'primary_color': [0, 0, 0, 0], 'secondary_color': [0, 0, 0, 0], 'secondary_color_rel': [0, 0, 0, 0], 'shifted_primary_color': [0, 0, 0, 0], 'tertiary_colors': {}}),
        ),
    ]
