# Generated by Django 5.0 on 2024-01-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0010_remove_cosmetic_color_shift_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='color_data',
            field=models.JSONField(default={'auto_find_colors': True, 'color_correct': True, 'constant_colors': {}, 'independent_color_shift': {}, 'is_color_shifted': False, 'linked_color_shift': {}, 'primary_color': [0, 0, 0, 0], 'shifted_primary_color': [0, 0, 0, 0], 'tertiary_colors': {}}),
        ),
    ]
