# Generated by Django 5.0 on 2024-01-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0011_alter_cosmetic_color_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='color_data',
            field=models.JSONField(default={'auto_find_colors': True, 'color_correct': True, 'constant_colors': {}, 'independent_color_shift': {}, 'is_color_shifted': False, 'new_base_color': [0, 0, 0, 1], 'true_colors': {}}),
        ),
    ]
