const history1 = document.getElementById(his1)
const history2 = document.getElementById(his2)
const history3 = document.getElementById(his3)
const history4 = document.getElementById(his4)
const history5 = document.getElementById(his5)